language: ruby
rvm:
- 2.1.0
script:
- RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec
before_script:
- psql -c 'create database bikewise_test' -U postgres
env:
  global:
    secure: BgIy8fbK84zYqjWgsk/zWk53Jgq5359smZ07hjae8XNT3dfD441nazcIBjOye6amCA6ddJiix+5gzcii8NWsIsOREtdM77xCxRIxtw6nbTTf2tTk4KwHWrHsq2xrLNNvOVksISOzw2NFLpZ7JmCLGrgAjABoVUEDFobn432l5cc=
